apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HelloWorld
  annotations:
    github.com/project-slug: eggcellent-365/HelloWorld
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: eggcellent-365
